const skills_keywords = [
    'javascript', 'python', 'java', 'c++', 'c#', 'html', 'css', 'react', 'angular', 'vue',
    'node.js', 'express.js', 'django', 'flask', 'sql', 'mongodb', 'postgresql',
    'agile', 'scrum', 'docker', 'aws', 'azure', 'machine learning', 'data analysis', 'data visualization',
    'problem-solving', 'teamwork', 'communication', 'leadership', 'project management', 'time management',
    'frontend', 'backend', 'UI/UX design', 'mobile app development', 'web development',
    'networking', 'security', 'cloud computing', 'artificial intelligence', 'natural language processing',
    'algorithm design', 'database management', 'data mining', 'statistics', 'data engineering',
    'testing', 'debugging', 'agile methodologies', 'software development', 'version control', 'RESTful APIs',
    'problem solving', 'critical thinking', 'customer service', 'technical support', 'system administration',
    'video editing', 'adobe premiere pro', 'final cut pro', 'after effects', 'davinci resolve',
    'video production', 'motion graphics', 'color grading', 'audio editing', 'storyboarding',
    'visual effects',
    'transitions',
    'animation',
    'cinematography',
    'timeline editing',
    'PHP',
    'Ruby',
    'Perl',
    'Rust',
    'Go',
    'Swift',
    'TypeScript',
    'Shell scripting',
    'Bash',
    'PowerShell',
    'Scala',
    'Kotlin',
    'Objective-C',
    'MATLAB',
    'Haskell',
    'Lua',
    'Groovy',
    'C',
    'Assembly language',
    'VBA',
    'VB.NET',
    'Visual Basic',
    'ASP.NET',
    'Ruby on Rails',
    'Spring',
    'Hibernate',
    'Laravel',
    'CodeIgniter',
    'Symfony',
    'CakePHP',
    'Django REST Framework',
    'Flask-RESTful',
    'GraphQL',
    'Firebase',
    'SQLite',
    'MySQL',
    'Oracle',
    'Microsoft SQL Server',
    'MariaDB',
    'Amazon RDS',
    'Redis',
    'Elasticsearch',
    'Cassandra',
    'Neo4j',
    'Hadoop',
    'Spark',
    'Apache Kafka',
    'MongoDB Atlas',
    'Google Cloud Firestore',
    'Microsoft Azure Cosmos DB',
    'Git',
    'Subversion (SVN)',
    'Mercurial',
    'Jenkins',
    'Travis CI',
    'CircleCI',
    'Mocha',
    'Jasmine',
    'JUnit',
    'Selenium',
    'Pytest',
    'Load testing',
    'Continuous integration',
    'Continuous deployment',
    'DevOps',
    'Kubernetes',
    'Ansible',
    'Terraform',
    'Chef',
    'Puppet',
    'Google Cloud Platform (GCP)',
    'Microsoft Azure',
    'IBM Cloud',
    'Docker Swarm',
    'Red Hat OpenShift',
    'Natural Language Understanding (NLU)',
    'Speech recognition',
    'Computer vision',
    'Predictive modeling',
    'Deep learning',
    'Reinforcement learning',
    'Neural networks',
    'Decision trees',
    'Random forests',
    'Support Vector Machines (SVM)',
    'Naive Bayes',
    'K-means clustering',
    'Principal Component Analysis (PCA)',
    'Apache Hadoop',
    'Apache Spark',
    'Tableau',
    'Power BI',
    'D3.js',
    'Plotly',
    'Matplotlib',
    'Seaborn',
    'Pandas',
    'NumPy',
    'SciPy',
    'Scikit-learn',
    'Excel',
    'Google Sheets',
    'Data preprocessing',
    'Feature engineering',
    'Data wrangling',
    'Data warehousing',
    'ETL (Extract, Transform, Load)',
    'Data visualization',
    'Data storytelling',
    'Big data analytics',
    'Statistical analysis',
    'A/B testing',
    'Time series analysis',
    'Survival analysis',
    'Regression analysis',
    'Classification',
    'Clustering',
    'Association rules',
    'Anomaly detection',
    'Data mining',
    'Dimensionality reduction',
    'Cloud engineering',
    'Infrastructure as Code (IaC)',
    'Serverless computing',
    'Microservices architecture',
    'API development',
    'RESTful architecture',
    'OAuth',
    'OpenAPI/Swagger',
    'Websockets',
    'Internet of Things (IoT)',
    'Blockchain',
    'Ethical hacking',
    'Vulnerability assessment',
    'Incident response',
    'Identity and Access Management (IAM)',
    'Network administration',
    'Firewalls',
    'Virtual private networks (VPNs)',
    'Penetration testing',
    'Security auditing',
    'Risk management',
    'Cryptography',
    'Artificial neural networks',
    'Recurrent neural networks',
    'Convolutional neural networks',
    'Generative adversarial networks (GANs)',
    'Transfer learning',
    'Image recognition',
    'Speech synthesis',
    'Text-to-speech',
    'Sentiment analysis',
    'Chatbots',
    'Recommendation systems',
    'Graph databases',
    'Relational databases',
    'NoSQL databases',
    'Data modeling',
    'Database optimization',
    'Data governance',
    'ETL (Extract, Transform, Load) processes',
    'Apache Kafka',
    'RabbitMQ',
    'Jupyter Notebook',
    'PyCharm',
    'Visual Studio Code',
    'Eclipse',
    'IntelliJ IDEA',
    'NetBeans',
    'Emacs',
    'Vim',
    'Unit testing',
    'Integration testing',
    'Performance testing',
    'Security testing',
    'Mobile testing',
    'Test automation',
    'Black box testing',
    'White box testing',
    'Gray box testing',
    'Usability testing',
    'Accessibility testing',
    'User acceptance testing',
    'Software development methodologies',
    'Waterfall',
    'Iterative',
    'Spiral',
    'Lean',
    'Extreme Programming (XP)',
    'Scrum',
    'Kanban',
    'User-centered design (UCD)',
    'Wireframing',
    'Prototyping',
    'Information architecture',
    'Interaction design',
    'User research',
    'Usability testing',
    'User personas',
    'Mobile app design',
    'Responsive web design',
    'Cross-platform development',
    'iOS development',
    'Android development',
    'React Native',
    'Flutter',
    'Ionic',
    'PhoneGap',
    'NativeScript',
    'Xamarin',
    'Ionic',
    'Windows app development',
    'macOS app development',
    'Linux app development',
    'Network protocols',
    'TCP/IP',
    'HTTP',
    'HTTPS',
    'DNS',
    'FTP',
    'SMTP',
    'POP3',
    'IMAP',
    'SSH',
    'SSL/TLS',
    'Load balancing',
    'CDN (Content Delivery Network)',
    'Web application security',
    'Authentication',
    'Authorization',
    'Cross-site scripting (XSS)',
    'Cross-site request forgery (CSRF)',
    'SQL injection',
    'Security information and event management (SIEM)',
    'Log analysis',
    'Backup and disaster recovery',
    'Change management',
    'Network monitoring',
    'Performance monitoring',
    'Asset management',
    'Cloud storage',
    'Video production',
    'Adobe Premiere Pro',
    'Final Cut Pro',
    'After Effects',
    'DaVinci Resolve',
    'Avid Media Composer',
    'Cinema 4D',
    'Motion design',
    'Video editing',
    'Color grading',
    'Audio editing',
    'Storyboarding',
    'Visual effects',
    'Transitions',
    'Animation',
    'Cinematography',
    'Timeline editing',
    'Green screen',
    'Sound design',
    'Music production',
    'Scriptwriting',
    'Directing',
    'Production management',
    'Digital marketing',
    'Search engine optimization (SEO)',
    'Search engine marketing (SEM)',
    'Social media marketing',
    'Content marketing',
    'Email marketing',
    'Influencer marketing',
    'Google Analytics',
    'Google AdWords',
    'Facebook Ads',
    'Instagram Ads',
    'LinkedIn Ads',
    'Twitter Ads',
    'Pinterest Ads',
    'YouTube Ads',
    'Affiliate marketing',
    'Conversion rate optimization',
    'Marketing automation',
    'Copywriting',
    'Graphic design',
    'Logo design',
    'Illustration',
    'Typography',
    'Print design',
    'Brand identity',
    'Packaging design',
    'User interface (UI) design',
    'User experience (UX) design',
    'Information design',
    'Mobile design',
    'Responsive design',
    'Design thinking',
    'Wireframing',
    'Prototyping',
    'Design systems',
    'Color theory',
    'Typography',
    'Grid systems',
    'Visual hierarchy',
    'User research',
    'User testing',
    'A/B testing',
    'Heatmaps',
    'Storyboarding',
    'Interaction design',
    'Design tools (Sketch, Figma, Adobe XD)',
    'Print production',
    'Layout design',
    'Image editing',
    'Color management',
    'Print finishing',
    'Print quality control',
    'Prepress',
    'Binding and finishing',
    'Print technologies (offset, digital, flexography)',
    'Print project management',
    'Print industry standards',
    'Print file formats',
    'Print production software (Adobe InDesign, Illustrator, Photoshop)',
    'Print equipment operation',
    'Print workflow optimization',
    'Print cost estimation',
    'Print marketing',
    'Direct mail',
    'Large format printing',
    'Print on demand',
    'Variable data printing',
    'Print advertising',
    'Print collateral',
    'Print publishing',
    'Print distribution',
    'Print vendor management',
    'Ruby on Rails',
    'Spring',
    'Hibernate',
    'Laravel',
    'CodeIgniter',
    'Symfony',
    'CakePHP',
    'Django REST Framework',
    'Flask-RESTful',
    'GraphQL',
    'Firebase',
    'SQLite',
    'MySQL',
    'Oracle',
    'Microsoft SQL Server',
    'MariaDB',
    'Amazon RDS',
    'Redis',
    'Elasticsearch',
    'Cassandra',
    'Neo4j',
    'Hadoop',
    'Spark',
    'Apache Kafka',
    'MongoDB Atlas',
    'Google Cloud Firestore',
    'Microsoft Azure Cosmos DB',
    'Git',
    'Subversion (SVN)',
    'Mercurial',
    'Jenkins',
    'Travis CI',
    'CircleCI',
    'Mocha',
    'Jasmine',
    'JUnit',
    'Selenium',
    'Pytest',
    'Load testing',
    'Continuous integration',
    'Continuous deployment',
    'DevOps',
    'Kubernetes',
    'Ansible',
    'Terraform',
    'Chef',
    'Puppet',
    'Google Cloud Platform (GCP)',
    'Microsoft Azure',
    'IBM Cloud',
    'Docker Swarm',
    'Red Hat OpenShift',
    'Natural Language Understanding (NLU)',
    'Speech recognition',
    'Computer vision',
    'Predictive modeling',
    'Deep learning',
    'Reinforcement learning',
    'Neural networks',
    'Decision trees',
    'Random forests',
    'Support Vector Machines (SVM)',
    'Naive Bayes',
    'K-means clustering',
    'Principal Component Analysis (PCA)',
    'Apache Hadoop',
    'Apache Spark',
    'Tableau',
    'Power BI',
    'D3.js',
    'Plotly',
    'Matplotlib',
    'Seaborn',
    'Pandas',
    'NumPy',
    'SciPy',
    'Scikit-learn',
    'Excel',
    'Google Sheets',
    'Data preprocessing',
    'Feature engineering',
    'Data wrangling',
    'Data warehousing',
    'ETL (Extract, Transform, Load)',
    'Data visualization',
    'Data storytelling',
    'Big data analytics',
    'Statistical analysis',
    'A/B testing',
    'Time series analysis',
    'Survival analysis',
    'Regression analysis',
    'Classification',
    'Clustering',
    'Association rules',
    'Anomaly detection',
    'Data mining',
    'Dimensionality reduction',
    'Cloud engineering',
    'Infrastructure as Code (IaC)',
    'Serverless computing',
    'Microservices architecture',
    'API development',
    'RESTful architecture',
    'OAuth',
    'OpenAPI/Swagger',
    'Websockets',
    'Internet of Things (IoT)',
    'Blockchain',
    'Ethical hacking',
    'Vulnerability assessment',
    'Incident response',
    'Identity and Access Management (IAM)',
    'Network administration',
    'Firewalls',
    'Virtual private networks (VPNs)',
    'Penetration testing',
    'Security auditing',
    'Risk management',
    'Cryptography',
    'Artificial neural networks',
    'Recurrent neural networks',
    'Convolutional neural networks',
    'Generative adversarial networks (GANs)',
    'Transfer learning',
    'Image recognition',
    'Speech synthesis',
    'Text-to-speech',
    'Sentiment analysis',
    'Chatbots',
    'Recommendation systems',
    'Graph databases',
    'Relational databases',
    'NoSQL databases',
    'Data modeling',
    'Database optimization',
    'Data governance',
    'ETL (Extract, Transform, Load) processes',
    'RabbitMQ',
    'Jupyter Notebook',
    'PyCharm',
    'Visual Studio Code',
    'Eclipse',
    'IntelliJ IDEA',
    'NetBeans',
    'Emacs',
    'Vim',
    'Unit testing',
    'Integration testing',
    'Performance testing',
    'Security testing',
    'Mobile testing',
    'Test automation',
    'Black box testing',
    'White box testing',
    'Gray box testing',
    'Usability testing',
    'Accessibility testing',
    'User acceptance testing',
    'Software development methodologies',
    'Waterfall',
    'Iterative',
    'Spiral',
    'Lean',
    'Extreme Programming (XP)',
    'Scrum',
    'Kanban',
    'User-centered design (UCD)',
    'Wireframing',
    'Prototyping',
    'Information architecture',
    'Interaction design',
    'User research',
    'Usability testing',
    'User personas',
    'Mobile app design',
    'Responsive web design',
    'Cross-platform development',
    'iOS development',
    'Android development',
    'React Native',
    'Flutter',
    'Ionic',
    'PhoneGap',
    'NativeScript',
    'Xamarin',
    'Windows app development',
    'macOS app development',
    'Linux app development',
    'Network protocols',
    'TCP/IP',
    'HTTP',
    'HTTPS',
    'DNS',
    'FTP',
    'SMTP',
    'POP3',
    'IMAP',
    'SSH',
    'SSL/TLS',
    'Load balancing',
    'CDN (Content Delivery Network)',
    'Web application security',
    'Authentication',
    'Authorization',
    'Cross-site scripting (XSS)',
    'Cross-site request forgery (CSRF)',
    'SQL injection',
    'Security information and event management (SIEM)',
    'Log analysis',
    'Backup and disaster recovery',
    'Change management',
    'Network monitoring',
    'Performance monitoring',
    'Asset management',
    'Cloud storage',
    'Video production',
    'Adobe Premiere Pro',
    'Final Cut Pro',
    'After Effects',
    'DaVinci Resolve',
    'Avid Media Composer',
    'Cinema 4D',
    'Motion design',
    'Video editing',
    'Color grading',
    'Audio editing',
    'Storyboarding',
    'Visual effects',
    'Transitions',
    'Animation',
    'Cinematography',
    'Timeline editing',
    'Green screen',
    'Sound design',
    'Music production',
    'Scriptwriting',
    'Directing',
    'Production management',
    'Digital marketing',
    'Search engine optimization (SEO)',
    'Search engine marketing (SEM)',
    'Social media marketing',
    'Content marketing',
    'Email marketing',
    'Influencer marketing',
    'Google Analytics',
    'Google AdWords',
    'Facebook Ads',
    'Instagram Ads',
    'LinkedIn Ads',
    'Twitter Ads',
    'Pinterest Ads',
    'YouTube Ads',
    'Affiliate marketing',
    'Conversion rate optimization',
    'Marketing automation',
    'Copywriting',
    'Graphic design',
    'Logo design',
    'Illustration',
    'Typography',
    'Print design',
    'Brand identity',
    'Packaging design',
    'User interface (UI) design',
    'User experience (UX) design',
    'Information design',
    'Mobile design',
    'Responsive design',
    'Design thinking',
    'Design systems',
    'Color theory',
    'Grid systems',
    'Visual hierarchy',
    'User research',
    'User testing',
    'A/B testing',
    'Heatmaps',
    'Storyboarding',
    'Interaction design',
    'Design tools (Sketch, Figma, Adobe XD)',
    'Print production',
    'Layout design',
    'Image editing',
    'Color management',
    'Print finishing',
    'Print quality control',
    'Prepress',
    'Binding and finishing',
    'Print technologies (offset, digital, flexography)',
    'Print project management',
    'Print industry standards',
    'Print file formats',
    'Print production software (Adobe InDesign, Illustrator, Photoshop)',
    'Print equipment operation',
    'Print workflow optimization',
    'Print cost estimation',
    'Print marketing',
    'Direct mail',
    'Large format printing',
    'Print on demand',
    'Variable data printing',
    'Print advertising',
    'Print collateral',
    'Print publishing',
    'Print distribution',
    'Print vendor management',
    'Content strategy',
    'Social media management',
    'Google Ads',
    'Conversion rate optimization (CRO)',
    'Pay-per-click (PPC) advertising',
    'Mobile marketing',
    'Video marketing',
    'Online reputation management',
    'Customer relationship management (CRM)',
    'Salesforce',
    'HubSpot',
    'Mailchimp',
    'WordPress',
    'Shopify',
    'Magento',
    'WooCommerce',
    'BigCommerce',
    'Squarespace',
    'Wix',
    'Adobe Creative Suite',
    'Photoshop',
    'Illustrator',
    'InDesign',
    'Premiere Pro',
    'Lightroom',
    'Canva',
    'Figma',
    'Sketch',
    'Zeplin',
    'Visual design',
    'Storytelling',
    'Environmental design',
    'Photography',
    'UI/UX design',
    'Front-end development',
    'Back-end development',
    'Full-stack development',
    'Cross-browser compatibility',
    'Progressive web apps',
    'RESTful APIs',
    'JSON',
    'XML',
    'Webpack',
    'Gulp',
    'Grunt',
    'Babel',
    'npm',
    'Yarn',
    'Version control',
    'GitHub',
    'Bitbucket',
    'Code review',
    'Bug tracking',
    'Agile methodologies',
    'Project management',
    'Jira',
    'Trello',
    'Asana',
    'Basecamp',
    'Microsoft Project',
    'Time management',
    'Critical thinking',
    'Problem-solving',
    'Decision-making',
    'Analytical skills',
    'Attention to detail',
    'Leadership',
    'Collaboration',
    'Communication',
    'Teamwork',
    'Conflict resolution',
    'Customer service',
    'Negotiation',
    'Public speaking',
    'Presentation skills',
    'Emotional intelligence',
    'Stakeholder management',
    'Vendor management',
    'Data analysis',
    'Data interpretation',
    'Machine learning',
    'Natural language processing (NLP)',
    'Big data',
    'Cloud computing',
    'Amazon Web Services (AWS)',
    'Docker',
    'Serverless architecture',
    'Microservices',
    'Virtualization',
    'Cybersecurity',
    'Network security',
    'Intrusion detection and prevention systems (IDS/IPS)',
    'Security incident and event management (SIEM)',
    'Encryption',
    'Public key infrastructure (PKI)',
    'Secure coding practices',
    'Risk assessment',
    'Disaster recovery',
    'Business continuity planning',
    'Forensics',
    'Compliance',
    'Regulatory standards (PCI-DSS, HIPAA, GDPR)',
    'Machine vision',
    'Image processing',
    'Object recognition',
    '3D modeling',
    'Virtual reality (VR)',
    'Augmented reality (AR)',
    'Game development',
    'Unity',
    'Unreal Engine',
    'Mobile app development',
    'Swift',
    'Java',
    'Kotlin',
    'Objective-C',
    'C#',
    'Blockchain technology',
    'Smart contracts',
    'Cryptocurrency',
    'Decentralized applications (DApps)',
    'Quantum computing',
    'Geographic Information System (GIS)',
    'Geospatial analysis',
    'Remote sensing',
    'Geocoding',
    'Geolocation',
    'Global Positioning System (GPS)',
    'Spatial databases',
    'Cartography',
    'Map design',
    'Geostatistics',
    'Routing algorithms',
    'Location-based services',
    'Traffic analysis',
    'Transportation planning',
    'Supply chain management',
    'Inventory management',
    'Logistics',
    'Procurement',
    'Demand forecasting',
    'Warehouse management',
    'Supplier relationship management',
    'Quality management',
    'Lean Six Sigma',
    'Process improvement',
    'Operations research',
    'Business process modeling',
    'Business intelligence',
    'Dashboarding',
    'Data quality management',
    'Predictive analytics',
    'Prescriptive analytics',
    'Descriptive analytics',
    'Quantitative analysis',
    'Qualitative analysis',
    'Market research',
    'Competitive analysis',
    'Financial analysis',
    'Investment analysis',
    'Risk analysis',
    'Business valuation',
    'Financial modeling',
    'Econometrics',
    'Supply chain analytics',
    'HR analytics',
    'Sales analytics',
    'Marketing analytics',
    'Customer analytics',
    'Product analytics',
    'Sustainability analytics',
    'Social media analytics',
    'Web analytics',
    'Regulatory standards',
    'Audit and assurance',
    'Financial reporting',
    'Internal controls',
    'Taxation',
    'Corporate finance',
    'Investment management',
    'Financial planning',
    'Financial forecasting',
    'Mergers and acquisitions (M&A)',
    'Capital budgeting',
    'Cost accounting',
    'Managerial accounting',
    'Budgeting and forecasting',
    'Variance analysis',
    'Activity-based costing (ABC)',
    'Strategic planning',
    'Business development',
    'Market entry strategies',
    'Corporate strategy',
    'SWOT analysis',
    'Scenario planning',
    'Organizational development',
    'Employee engagement',
    'Talent management',
    'Leadership development',
    'Performance management',
    'Human resources management',
    'Employee relations',
    'Compensation and benefits',
    'Learning and development',
    'Employee wellness',
    'Workforce planning',
    'Employee onboarding',
    'Succession planning',
    'Knowledge management',
    'Intellectual property',
    'Licensing and royalties',
    'Patent law',
    'Copyright law',
    'Trademark law',
    'Contracts',
    'Dispute resolution',
    'Legal research',
    'Legal writing',
    'Litigation',
    'Privacy and data protection',
    'Ethics and compliance',
    'Corporate governance',
    'Environmental sustainability',
    'Social responsibility',
    'International business',
    'Global marketing',
    'International trade',
    'Foreign exchange',
    'Export-import procedures',
    'Trade finance',
    'Country-specific regulations',
    'Cultural intelligence',
    'Business etiquette',
    'Foreign languages'
];

module.exports = skills_keywords;